{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import os\n",
    "import logging\n",
    "import json\n",
    "\n",
    "from tradingdb.utils import *\n",
    "from tradingdb.ORM.utils import *\n",
    "from sqlalchemy import exc\n",
    "import sqlite3\n",
    "\n",
    "\n",
    "logger = logging.getLogger()\n",
    "logger.setLevel(logging.INFO)\n",
    "handler = logging.StreamHandler()\n",
    "handler.setLevel(logging.NOTSET)\n",
    "format = logging.Formatter('%(name)s - %(levelname)s - %(message)s')\n",
    "handler.setFormatter(format)\n",
    "\n",
    "logger.addHandler(handler)\n",
    "\n",
    "from datetime import datetime, timedelta\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Params"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "intervals_to_add=['1d']\n",
    "DBNAME=os.path.abspath(\"../data/master.db\")\n",
    "deltadays=14"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-07-24 08:00:11 2023-08-07 04:30:11\n"
     ]
    }
   ],
   "source": [
    "time_end=datetime.today().replace(hour=4, minute=30, microsecond=0)\n",
    "# covid crisis: start new era from ftse slump (23 march)\n",
    "time_start = time_end - timedelta(days=deltadays)\n",
    "time_start=time_start.replace(hour=8, minute=0, microsecond=0)\n",
    "print(time_start,time_end)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "89 0\n",
      "AAF.L 1d\n",
      "[*********************100%***********************]  1 of 1 completed\n",
      "AAF.L 1d 2023-07-24 00:00:00 not inserted\n",
      "AAF.L 1d 2023-07-25 00:00:00 not inserted\n",
      "AAF.L 1d 2023-07-26 00:00:00 not inserted\n",
      "AAF.L 1d 2023-07-27 00:00:00 not inserted\n",
      "AAF.L 1d 2023-07-28 00:00:00 not inserted\n",
      "AAF.L 1d 2023-08-01 00:00:00 not inserted\n",
      "AAF.L 1d 2023-08-02 00:00:00 not inserted\n",
      "AAF.L 1d 2023-08-03 00:00:00 not inserted\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <sqlite3.Connection object at 0x195086d50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 260, in _close_connection\n",
      "    self._dialect.do_terminate(connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 689, in do_terminate\n",
      "    self.do_close(dbapi_connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 692, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <sqlite3.Connection object at 0x195086d50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 260, in _close_connection\n",
      "    self._dialect.do_terminate(connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 689, in do_terminate\n",
      "    self.do_close(dbapi_connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 692, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "sqlalchemy.pool.impl.NullPool - ERROR - Exception closing connection <sqlite3.Connection object at 0x195086d50>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 757, in _finalize_fairy\n",
      "    fairy._reset(pool, transaction_was_reset)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 1016, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 683, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 260, in _close_connection\n",
      "    self._dialect.do_terminate(connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 689, in do_terminate\n",
      "    self.do_close(dbapi_connection)\n",
      "  File \"/Users/davidebranduardi/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 692, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4685217280 and this is thread id 123145552912384.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AAF.L 1d 2023-08-04 00:00:00 not inserted\n",
      "36 0\n",
      "AAL.L 1d\n",
      "[*********************100%***********************]  1 of 1 completed\n",
      "AAL.L 1d 2023-07-24 00:00:00 not inserted\n",
      "AAL.L 1d 2023-07-25 00:00:00 not inserted\n",
      "AAL.L 1d 2023-07-26 00:00:00 not inserted\n",
      "AAL.L 1d 2023-07-27 00:00:00 not inserted\n",
      "AAL.L 1d 2023-07-28 00:00:00 not inserted\n",
      "AAL.L 1d 2023-07-31 00:00:00 not inserted\n",
      "AAL.L 1d 2023-08-01 00:00:00 not inserted\n",
      "AAL.L 1d 2023-08-02 00:00:00 not inserted\n",
      "AAL.L 1d 2023-08-03 00:00:00 not inserted\n",
      "AAL.L 1d 2023-08-04 00:00:00 not inserted\n",
      "108 0\n",
      "AAPL 1d\n",
      "[*********************100%***********************]  1 of 1 completed\n",
      "AAPL 1d 2023-07-24 00:00:00 not inserted\n",
      "AAPL 1d 2023-07-25 00:00:00 not inserted\n",
      "AAPL 1d 2023-07-26 00:00:00 not inserted\n",
      "AAPL 1d 2023-07-27 00:00:00 not inserted\n",
      "AAPL 1d 2023-07-28 00:00:00 not inserted\n",
      "AAPL 1d 2023-08-01 00:00:00 not inserted\n",
      "AAPL 1d 2023-08-02 00:00:00 not inserted\n",
      "AAPL 1d 2023-08-03 00:00:00 not inserted\n",
      "AAPL 1d 2023-08-04 00:00:00 not inserted\n",
      "25 0\n",
      "ABDN.L 1d\n",
      "[*********************100%***********************]  1 of 1 completed\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1900\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1899\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1900\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   1901\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1902\u001b[0m         )\n\u001b[1;32m   1904\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py:736\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    735\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdo_execute\u001b[39m(\u001b[39mself\u001b[39m, cursor, statement, parameters, context\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m--> 736\u001b[0m     cursor\u001b[39m.\u001b[39;49mexecute(statement, parameters)\n",
      "\u001b[0;31mOperationalError\u001b[0m: database is locked",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[41], line 53\u001b[0m\n\u001b[1;32m     51\u001b[0m     \u001b[39mprint\u001b[39m(sid,\u001b[39mlen\u001b[39m(ret))\n\u001b[1;32m     52\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mlen\u001b[39m(ret)\u001b[39m==\u001b[39m\u001b[39m0\u001b[39m:\n\u001b[0;32m---> 53\u001b[0m         retrieve_new_period_for_sid(session,sid,time_start,time_end,ival)\n\u001b[1;32m     54\u001b[0m         \u001b[39m#break\u001b[39;00m\n\u001b[1;32m     55\u001b[0m \u001b[39m#break\u001b[39;00m\n",
      "Cell \u001b[0;32mIn[41], line 25\u001b[0m, in \u001b[0;36mretrieve_new_period_for_sid\u001b[0;34m(session, sid, time_start, time_end, ival)\u001b[0m\n\u001b[1;32m     14\u001b[0m     p\u001b[39m=\u001b[39mstock\u001b[39m.\u001b[39mPrice(\n\u001b[1;32m     15\u001b[0m                 stock_id\u001b[39m=\u001b[39msid,\n\u001b[1;32m     16\u001b[0m                 period_id\u001b[39m=\u001b[39mpid,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     22\u001b[0m                 adjusted_close\u001b[39m=\u001b[39mrow[\u001b[39m'\u001b[39m\u001b[39mAdj Close\u001b[39m\u001b[39m'\u001b[39m],\n\u001b[1;32m     23\u001b[0m                 volume\u001b[39m=\u001b[39mrow[\u001b[39m'\u001b[39m\u001b[39mVolume\u001b[39m\u001b[39m'\u001b[39m])\n\u001b[1;32m     24\u001b[0m     subsession\u001b[39m.\u001b[39madd(p)\n\u001b[0;32m---> 25\u001b[0m     subsession\u001b[39m.\u001b[39;49mflush()\n\u001b[1;32m     26\u001b[0m \u001b[39mexcept\u001b[39;00m sqlite3\u001b[39m.\u001b[39mIntegrityError \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m     27\u001b[0m     subsession\u001b[39m.\u001b[39mrollback()  \u001b[39m# Rollback the changes to avoid leaving the session in an invalid state\u001b[39;00m\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py:3444\u001b[0m, in \u001b[0;36mSession.flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   3442\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   3443\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_flushing \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m-> 3444\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_flush(objects)\n\u001b[1;32m   3445\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m   3446\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_flushing \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py:3584\u001b[0m, in \u001b[0;36mSession._flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   3582\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[1;32m   3583\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m-> 3584\u001b[0m         transaction\u001b[39m.\u001b[39mrollback(_capture_exception\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[0;34m(self, type_, value, traceback)\u001b[0m\n\u001b[1;32m     68\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[0;32m---> 70\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[1;32m     71\u001b[0m             exc_value,\n\u001b[1;32m     72\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[1;32m     73\u001b[0m         )\n\u001b[1;32m     74\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m     75\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[1;32m     76\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[1;32m     77\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py:211\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    208\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[1;32m    210\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 211\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[1;32m    212\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m    213\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[1;32m    214\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    215\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    216\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py:3544\u001b[0m, in \u001b[0;36mSession._flush\u001b[0;34m(self, objects)\u001b[0m\n\u001b[1;32m   3542\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_warn_on_events \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[1;32m   3543\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 3544\u001b[0m     flush_context\u001b[39m.\u001b[39;49mexecute()\n\u001b[1;32m   3545\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m   3546\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_warn_on_events \u001b[39m=\u001b[39m \u001b[39mFalse\u001b[39;00m\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py:456\u001b[0m, in \u001b[0;36mUOWTransaction.execute\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    454\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    455\u001b[0m     \u001b[39mfor\u001b[39;00m rec \u001b[39min\u001b[39;00m topological\u001b[39m.\u001b[39msort(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdependencies, postsort_actions):\n\u001b[0;32m--> 456\u001b[0m         rec\u001b[39m.\u001b[39;49mexecute(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py:630\u001b[0m, in \u001b[0;36mSaveUpdateAll.execute\u001b[0;34m(self, uow)\u001b[0m\n\u001b[1;32m    628\u001b[0m \u001b[39m@util\u001b[39m\u001b[39m.\u001b[39mpreload_module(\u001b[39m\"\u001b[39m\u001b[39msqlalchemy.orm.persistence\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    629\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mexecute\u001b[39m(\u001b[39mself\u001b[39m, uow):\n\u001b[0;32m--> 630\u001b[0m     util\u001b[39m.\u001b[39;49mpreloaded\u001b[39m.\u001b[39;49morm_persistence\u001b[39m.\u001b[39;49msave_obj(\n\u001b[1;32m    631\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmapper,\n\u001b[1;32m    632\u001b[0m         uow\u001b[39m.\u001b[39;49mstates_for_mapper_hierarchy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmapper, \u001b[39mFalse\u001b[39;49;00m, \u001b[39mFalse\u001b[39;49;00m),\n\u001b[1;32m    633\u001b[0m         uow,\n\u001b[1;32m    634\u001b[0m     )\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py:245\u001b[0m, in \u001b[0;36msave_obj\u001b[0;34m(base_mapper, states, uowtransaction, single)\u001b[0m\n\u001b[1;32m    233\u001b[0m     update \u001b[39m=\u001b[39m _collect_update_commands(\n\u001b[1;32m    234\u001b[0m         uowtransaction, table, states_to_update\n\u001b[1;32m    235\u001b[0m     )\n\u001b[1;32m    237\u001b[0m     _emit_update_statements(\n\u001b[1;32m    238\u001b[0m         base_mapper,\n\u001b[1;32m    239\u001b[0m         uowtransaction,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    242\u001b[0m         update,\n\u001b[1;32m    243\u001b[0m     )\n\u001b[0;32m--> 245\u001b[0m     _emit_insert_statements(\n\u001b[1;32m    246\u001b[0m         base_mapper,\n\u001b[1;32m    247\u001b[0m         uowtransaction,\n\u001b[1;32m    248\u001b[0m         mapper,\n\u001b[1;32m    249\u001b[0m         table,\n\u001b[1;32m    250\u001b[0m         insert,\n\u001b[1;32m    251\u001b[0m     )\n\u001b[1;32m    253\u001b[0m _finalize_insert_update_commands(\n\u001b[1;32m    254\u001b[0m     base_mapper,\n\u001b[1;32m    255\u001b[0m     uowtransaction,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    271\u001b[0m     ),\n\u001b[1;32m    272\u001b[0m )\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py:1238\u001b[0m, in \u001b[0;36m_emit_insert_statements\u001b[0;34m(base_mapper, uowtransaction, mapper, table, insert, bookkeeping)\u001b[0m\n\u001b[1;32m   1232\u001b[0m     result \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39m_execute_20(\n\u001b[1;32m   1233\u001b[0m         statement\u001b[39m.\u001b[39mvalues(value_params),\n\u001b[1;32m   1234\u001b[0m         params,\n\u001b[1;32m   1235\u001b[0m         execution_options\u001b[39m=\u001b[39mexecution_options,\n\u001b[1;32m   1236\u001b[0m     )\n\u001b[1;32m   1237\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> 1238\u001b[0m     result \u001b[39m=\u001b[39m connection\u001b[39m.\u001b[39;49m_execute_20(\n\u001b[1;32m   1239\u001b[0m         statement,\n\u001b[1;32m   1240\u001b[0m         params,\n\u001b[1;32m   1241\u001b[0m         execution_options\u001b[39m=\u001b[39;49mexecution_options,\n\u001b[1;32m   1242\u001b[0m     )\n\u001b[1;32m   1244\u001b[0m primary_key \u001b[39m=\u001b[39m result\u001b[39m.\u001b[39minserted_primary_key\n\u001b[1;32m   1245\u001b[0m \u001b[39mif\u001b[39;00m primary_key \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1705\u001b[0m, in \u001b[0;36mConnection._execute_20\u001b[0;34m(self, statement, parameters, execution_options)\u001b[0m\n\u001b[1;32m   1701\u001b[0m     util\u001b[39m.\u001b[39mraise_(\n\u001b[1;32m   1702\u001b[0m         exc\u001b[39m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[39m=\u001b[39merr\n\u001b[1;32m   1703\u001b[0m     )\n\u001b[1;32m   1704\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m-> 1705\u001b[0m     \u001b[39mreturn\u001b[39;00m meth(\u001b[39mself\u001b[39;49m, args_10style, kwargs_10style, execution_options)\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py:334\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    330\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_execute_on_connection\u001b[39m(\n\u001b[1;32m    331\u001b[0m     \u001b[39mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m\n\u001b[1;32m    332\u001b[0m ):\n\u001b[1;32m    333\u001b[0m     \u001b[39mif\u001b[39;00m _force \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msupports_execution:\n\u001b[0;32m--> 334\u001b[0m         \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39;49m_execute_clauseelement(\n\u001b[1;32m    335\u001b[0m             \u001b[39mself\u001b[39;49m, multiparams, params, execution_options\n\u001b[1;32m    336\u001b[0m         )\n\u001b[1;32m    337\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    338\u001b[0m         \u001b[39mraise\u001b[39;00m exc\u001b[39m.\u001b[39mObjectNotExecutableError(\u001b[39mself\u001b[39m)\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1572\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   1560\u001b[0m compiled_cache \u001b[39m=\u001b[39m execution_options\u001b[39m.\u001b[39mget(\n\u001b[1;32m   1561\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mcompiled_cache\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_compiled_cache\n\u001b[1;32m   1562\u001b[0m )\n\u001b[1;32m   1564\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[39m=\u001b[39m elem\u001b[39m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   1565\u001b[0m     dialect\u001b[39m=\u001b[39mdialect,\n\u001b[1;32m   1566\u001b[0m     compiled_cache\u001b[39m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1570\u001b[0m     linting\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39mcompiler_linting \u001b[39m|\u001b[39m compiler\u001b[39m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   1571\u001b[0m )\n\u001b[0;32m-> 1572\u001b[0m ret \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_context(\n\u001b[1;32m   1573\u001b[0m     dialect,\n\u001b[1;32m   1574\u001b[0m     dialect\u001b[39m.\u001b[39;49mexecution_ctx_cls\u001b[39m.\u001b[39;49m_init_compiled,\n\u001b[1;32m   1575\u001b[0m     compiled_sql,\n\u001b[1;32m   1576\u001b[0m     distilled_params,\n\u001b[1;32m   1577\u001b[0m     execution_options,\n\u001b[1;32m   1578\u001b[0m     compiled_sql,\n\u001b[1;32m   1579\u001b[0m     distilled_params,\n\u001b[1;32m   1580\u001b[0m     elem,\n\u001b[1;32m   1581\u001b[0m     extracted_params,\n\u001b[1;32m   1582\u001b[0m     cache_hit\u001b[39m=\u001b[39;49mcache_hit,\n\u001b[1;32m   1583\u001b[0m )\n\u001b[1;32m   1584\u001b[0m \u001b[39mif\u001b[39;00m has_events:\n\u001b[1;32m   1585\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_execute(\n\u001b[1;32m   1586\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   1587\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1591\u001b[0m         ret,\n\u001b[1;32m   1592\u001b[0m     )\n",
      "File \u001b[0;32m~/Projects/Finance/trading-toolbox/tradingdb/tradingdb/condavenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py:1900\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1898\u001b[0m                 \u001b[39mbreak\u001b[39;00m\n\u001b[1;32m   1899\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1900\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdialect\u001b[39m.\u001b[39;49mdo_execute(\n\u001b[1;32m   1901\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1902\u001b[0m         )\n\u001b[1;32m   1904\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39m_has_events:\n\u001b[1;32m   1905\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mafter_cursor_execute(\n\u001b[1;32m   1906\u001b[0m         \u001b[39mself\u001b[39m,\n\u001b[1;32m   1907\u001b[0m         cursor,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1911\u001b[0m         context\u001b[39m.\u001b[39mexecutemany,\n\u001b[1;32m   1912\u001b[0m     )\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "\n",
    "def retrieve_new_period_for_sid(session,sid,time_start,time_end,ival):\n",
    "    # get the yf symbol\n",
    "    with session.begin() as mysession:\n",
    "        q=mysession.query(stock.Stock)\n",
    "        ret=q.filter(stock.Stock.id==sid).one()\n",
    "\n",
    "        pid=mysession.query(stock.Period.id).filter(stock.Period.name==ival).one()[0]\n",
    "\n",
    "        print(ret.yf_symbol,ival)\n",
    "        dfd=download_data_from_yfsymbols(ret.yf_symbol,time_start,time_end,interval=ival)\n",
    "        for index, row in dfd[ret.yf_symbol].iterrows():        \n",
    "            try:\n",
    "                subsession=session()\n",
    "                qq=subsession.query(stock.Price.id)\n",
    "                qq=qq.query()\n",
    "                p=stock.Price(\n",
    "                            stock_id=sid,\n",
    "                            period_id=pid,\n",
    "                            date=index.to_pydatetime(),  \n",
    "                            open=row['Open'],\n",
    "                            low=row['Low'],\n",
    "                            high=row['High'],\n",
    "                            close=row['Close'],\n",
    "                            adjusted_close=row['Adj Close'],\n",
    "                            volume=row['Volume'])\n",
    "                subsession.add(p)\n",
    "                subsession.flush()\n",
    "            except sqlite3.IntegrityError as e:\n",
    "                subsession.rollback()  # Rollback the changes to avoid leaving the session in an invalid state\n",
    "                print(ret.yf_symbol,ival,index.to_pydatetime(),\"not inserted\")\n",
    "                #print(\"IntegrityError: {}\".format(e))\n",
    "                #break\n",
    "                subsession.close()\n",
    "            except Exception as e:\n",
    "                subsession.rollback()  # Rollback the changes for other unexpected exceptions\n",
    "                #print(\"Unexpected error: {}\".format(e))\n",
    "                print(ret.yf_symbol,ival,index.to_pydatetime(),\"not inserted\")\n",
    "\n",
    "                #break\n",
    "                subsession.close()\n",
    "\n",
    "\n",
    "\n",
    "session=get_new_session(DBNAME)\n",
    "with session.begin() as mysession:\n",
    "    ret=mysession.query(stock.Stock.id).all()\n",
    "sids=[r[0] for r in ret]\n",
    "for ival in intervals_to_add:\n",
    "    for sid in sids:\n",
    "        with session.begin() as mysession:\n",
    "            q=mysession.query(stock.Stock).join(stock.Price).join(stock.Period)\n",
    "            ret=q.filter(stock.Stock.id==sid).filter(stock.Period==ival).all()\n",
    "        if len(ret)==0:\n",
    "            print(\"Retrieving interval for \",sid)\n",
    "\n",
    "            retrieve_new_period_for_sid(session,sid,time_start,time_end,ival)\n",
    "            #break\n",
    "    #break\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "with session.begin() as mysession:\n",
    "    mysession.rollback()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.15"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
